import { Store, Product } from '@/types/store';

export const DEMO_STORE_SLUG = 'panaderia-don-jose';

export const DEMO_STORE: Store = {
  id: 'demo_panaderia_don_jose',
  slug: DEMO_STORE_SLUG,
  name: 'Panadería Don José',
  category: 'Panadería y Pastelería',
  description: 'Pan artesanal de masa madre, croissants hojaldrados y pastelería fina horneada a diario. Haz tu pedido y recíbelo calientito en tu puerta.',
  whatsappPhone: '51999888777',
  ownerId: 'demo_user',
  status: 'activa',
  themeStyle: 'moderna',
  primaryColor: '#059669',
  createdAt: 1700000000000,
};

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-prod-1',
    storeId: 'demo_panaderia_don_jose',
    title: 'Pan Campesino de Masa Madre',
    description: 'Corteza crocante y miga aireada elaborada con harina orgánica y 24 horas de fermentación natural en piso de piedra.',
    price: 8.50,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: 1700000001000,
  },
  {
    id: 'demo-prod-2',
    storeId: 'demo_panaderia_don_jose',
    title: 'Croissant Francés de Mantequilla',
    description: 'Clásico croissant 100% hojaldrado con mantequilla pura artesanal. Dorado, ligero y crujiente.',
    price: 5.00,
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: 1700000002000,
  },
  {
    id: 'demo-prod-3',
    storeId: 'demo_panaderia_don_jose',
    title: 'Torta de Chocolate Húmeda (Porción)',
    description: 'Bizcocho extra húmedo relleno y bañado en abundante fudge artesanal de cacao peruano al 70%.',
    price: 12.00,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: 1700000003000,
  },
  {
    id: 'demo-prod-4',
    storeId: 'demo_panaderia_don_jose',
    title: 'Baguette Rústica Tradicional',
    description: 'Barra clásica elaborada a mano, fermentada lentamente y horneada al punto exacto de crocancia.',
    price: 4.50,
    imageUrl: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: 1700000004000,
  },
  {
    id: 'demo-prod-5',
    storeId: 'demo_panaderia_don_jose',
    title: 'Cinnamon Roll con Glaseado Crema',
    description: 'Rollo esponjoso con canela aromática, azúcar morena y cobertura cremosa de queso y vainilla.',
    price: 6.50,
    imageUrl: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: 1700000005000,
  },
  {
    id: 'demo-prod-6',
    storeId: 'demo_panaderia_don_jose',
    title: 'Empanada de Carne Artesanal',
    description: 'Masa suave horneada rellena con carne sazonada, cebolla caramelizada, huevo duro y aceituna.',
    price: 7.00,
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: 1700000006000,
  },
  {
    id: 'demo-prod-7',
    storeId: 'demo_panaderia_don_jose',
    title: 'Café Americano Especial 12oz',
    description: 'Granos de especialidad de Villa Rica recién molidos con notas dulces a chocolate y nueces.',
    price: 6.00,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: 1700000007000,
  },
  {
    id: 'demo-prod-8',
    storeId: 'demo_panaderia_don_jose',
    title: 'Pack Desayuno Familiar Don José',
    description: 'Incluye: 4 Panes Campesinos + 2 Croissants de Mantequilla + 1 Porción de Torta de Chocolate.',
    price: 24.90,
    imageUrl: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: 1700000008000,
  },
];
